### ISSUE TITLE
Implement node monitoring at project folder level

### ISSUE THREAD

**Issue by nexus6-haiku** [nexus6-haiku/Genio#20]
This lets the Project browser be updated when a change in the underlying file system folder occurs.
The Item representing the Project and all its children should change accordingly. However, in the near future there will be a link between each file and the corresponding Editor view therefore the whole entry in the BOutlineListView can't be simply removed and repopulated. Each item should be kept in sync with their respective entity in the file system when they are removed, added or renamed.

**Comment by Freaxed** [comment]
The technical way to implement this is to use the private api defined in the PathMonitor.h header file.

**Comment by nexus6-haiku** [comment]
Implemented and merged with main
