### ISSUE TITLE
Genio does not recognize and open unsupported files

### ISSUE THREAD

**Issue by nexus6-haiku** [nexus6-haiku/Genio#21]
If a file is not already identified by the Tracker, Genio fails too and does not open it.
This mainly occurs with plain text files.
If the file is identified from the Tracker (context menu -> Identify) then Genio is able to open it without issues.

**Comment by Freaxed** [comment]
Sorry but I cannot reproduce this. In the code, genio already does an 'identify' in case of missing mime information..

**Comment by nexus6-haiku** [comment]
I know but it happened before a few times. Try this please: there’s a file called NOTES in the root of the Paladin repository. This is the last file I’ve tried that caused the issue.

**Comment by Freaxed** [comment]
I cloned the Paladin repo but can't open it with the latest prohect-folders branch.. it crash..
![crash](https://user-images.githubusercontent.com/1453326/218491152-e549c4f9-09d9-405e-baf8-090f0d587fa9.png)

The other folders are opening OK!

**Comment by Freaxed** [comment]
ok, I see now: the code create a flatten bmessage with the same name as the folder name. Can't we just call it ".genio"?

**Comment by nexus6-haiku** [comment]
yes that was my intention, good spot!

**Comment by nexus6-haiku** [comment]
I spotted and fixed a problem with path that includes spaces because the parameter passed to /bin/open needs to be surrounded between quotes.
