### ISSUE TITLE
Genio crashed due to a crash in clangd

### ISSUE THREAD

**Issue by nexus6-haiku** [nexus6-haiku/Genio#29]
This occured once as of now, when I tried to add an include to GenioWindow.cpp, clangd crashed and Genio with it.

**Comment by nexus6-haiku** [comment]
[clangd-2041-debug-01-03-2023-13-44-56.report.txt](https://github.com/nexus6-haiku/Genio/files/10882684/clangd-2041-debug-01-03-2023-13-44-56.report.txt)

**Comment by Freaxed** [comment]
Is this reproducible? If so, would be worth running the application in
Trace log level ("Genio t")

Il giorno ven 3 mar 2023 alle ore 15:06 Davide Alfano <
***@***.***> ha scritto:

**Comment by nexus6-haiku** [comment]
No, I've tried to make the same exact steps I was doing before but it no longer crashes.

**Comment by nexus6-haiku** [comment]
It just crashed three times on the very same file while trying to rearrange the includes.

{T} FileStatus [file:///boot/home/develop/myprojects/IDE/Genio/src/ui/ProjectsFolderBrowser.cpp] [parsing includes, running DocumentLinks]
V[15:09:36.746] indexed preamble AST for /boot/home/develop/myprojects/IDE/Genio/src/ui/ProjectsFolderBrowser.cpp version 15:
  symbol slab: 7974 symbols, 2026216 bytes
  ref slab: 0 symbols, 0 refs, 128 bytes
  relations slab: 246 relations, 4376 bytes
V[15:09:36.909] Build dynamic index for header symbols with estimated memory usage of 4594200 bytes
V[15:09:36.923] Built preamble of size 1730416 for file /boot/home/develop/myprojects/IDE/Genio/src/ui/ProjectsFolderBrowser.cpp version 15
{T} Client: - snd 
{"id":"18107571874224_textDocument/hover","jsonrpc":"2.0","method":"textDocument/hover","params":{"position":{"character":0,"line":0},"textDocument":{"uri":"file:///boot/home/develop/myprojects/IDE/Genio/src/ui/ProjectsFolderBrowser.cpp"}}}

E[15:10:15.828] Transport error: I/O error
I[15:10:15.830] LSP finished, exiting with status 1

**Comment by nexus6-haiku** [comment]
can we close this?

**Comment by nexus6-haiku** [comment]
Why don't we close this bug and open a separate enhancement (maybe linked to it)?

**Comment by Freaxed** [comment]
I agree!

Il giorno ven 24 mar 2023 alle ore 10:17 Davide Alfano <
***@***.***> ha scritto:
