### ISSUE TITLE
Restore "Rescan project" feature

### ISSUE THREAD

**Issue by nexus6-haiku** [nexus6-haiku/Genio#30]
Originally, Genio supported a "Project rescan" feature which worked with the previous project management system.
It deleted the project node from the BOutlineListView and re-added it with its children after a full rescan of the folder.
Until we implement node monitoring on the Project folder, we need to restore that feature.

**Comment by nexus6-haiku** [comment]
I agree and I was about to add a whole hypothesis for this in line with your comment but we have to take into account that in the future we may want to implement node monitoring and "live" updates of the Project Browser.
Restoring the old behaviour should be done fairly easy while the enhanced one one may require a few days more.
Is it worth the extra effort?
Does the old behaviour break something in the LSP branch?

**Comment by Freaxed** [comment]
I see your points, and I agree it will take less effort in implementing it
the “old” way. Go this way if you want to take this task.
Some additional considerations: the delta logic must be anyway implemented
for the PathMonitoring; a rescan button must be anyway added  to force the
folder rescan.
About LSP: if the ProjectFolder object is destroyed, the clang process is
closed so If we follow the “close” project and “load” project sequence it
should work.

Il giorno mar 28 feb 2023 alle 17:19 Davide Alfano ***@***.***>
ha scritto:

**Comment by nexus6-haiku** [comment]
Closing this as a full path monitoring system with live updates is now in place, no need to rescan manually anymore.
