### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by jackburton79** [nexus6-haiku/Genio#41]
Would be nice to be able to change font size.
Best if it inherited the system font settings

**Comment by Freaxed** [comment]
I somehow fixed this.
By default (no configuration file) the font size is the system size (be_plain_font->Size()).
Updated also the Settings window to select the system font size or a specific size.
Zoom in/Zoom out always working.

OT: should we care about letting the user select the font type?

**Comment by jackburton79** [comment]
Nice One!
I think we should allow the user to choose the font, yes.
Is it high priority? Definitely not 😄

**Comment by jackburton79** [comment]
Fixed in a89872fd99a0869da1e0dc3cbef0bc45d247351f
