### ISSUE TITLE
Signature help: sometimes overload no. 1 does not show

### ISSUE THREAD

**Issue by nexus6-haiku** [nexus6-haiku/Genio#50]
Sometimes, the signature help box shows a number of overloads for a function (or a class constructor) but does not allow me to select the first one.
For example, the following code:

`fFileSearchControl = new BTextControl`

automatically summons the signature help box with four overloads, I can go through from 2 to 4 but not 1 neither with the arrows on the box itself nor with the arrow keys on the keyboard.

However, It does not happen all the time and I have not been able to reproduce it systematically.

**Comment by Freaxed** [comment]
If you run in debug or trace mode, would be useful to have the logs showing
the responses from clangd.

Il giorno mar 11 apr 2023 alle 14:18 Davide Alfano ***@***.***>
ha scritto:

**Comment by Freaxed** [comment]
Fixed in https://github.com/nexus6-haiku/Genio/commit/f0b11054edaa92281c475e364eaf17a8a48f7927
